# Generated by Django 5.0.3 on 2024-04-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcatagory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True),
        ),
    ]
